name: Continuous Integration
run-name: ${{ github.actor }} is building OpenMVS

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CTEST_OUTPUT_ON_FAILURE: 1

defaults:
  run:
    shell: bash

jobs:
  build-tests:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,  macOS-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows-release
            build-type: Release
          - os: ubuntu-latest
            triplet: x64-linux-release
            build-type: Release
          - os: macos-latest
            triplet: x64-osx
            build-type: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10.6
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '4cb4a5c5ddcb9de0c83c85837ee6974c8333f032'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y autoconf-archive libxmu-dev libdbus-1-dev libxtst-dev libxi-dev libxinerama-dev libxcursor-dev xorg-dev libgl-dev libglu1-mesa-dev pkg-config

      - name: Install macOS dependencies
        if: matrix.os == 'macOS-latest'
        run: |
          brew install automake autoconf-archive

      - name: Configure CMake
        run: |
          cmake -S . -B make -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}

      - name: Build
        working-directory: ./make
        run: |
          rm -rf ../vcpkg/buildtrees
          rm -rf ../vcpkg/downloads
          cmake --build . --config ${{ matrix.build-type }} --parallel $(nproc)

      - name: Unit Tests
        working-directory: ./make
        run: |
          ctest -j$(nproc) --build-config ${{ matrix.build-type }}

      - name: Zip Windows release
        if: matrix.os == 'windows-latest'
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          directory: ${{ github.workspace }}/make/bin/
          recursive_exclusions: '*.exp'
          filename: 'OpenMVS_Windows.zip'

      - name: Deploy Windows release
        if: matrix.os == 'windows-latest'
        uses: WebFreak001/deploy-nightly@v1.2.0
        id: deploynightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/cdcseacave/openMVS/releases/64600462/assets{?name,label}
          release_id: 64600462
          asset_path: ${{ github.workspace }}/make/bin/OpenMVS_Windows.zip
          asset_name: OpenMVS_Windows_x64_$$.zip
          asset_content_type: application/zip
          max_releases: 7

      - name: Display Windows release link
        if: matrix.os == 'windows-latest'
        run: |
          echo ${{steps.deploynightly.outputs.url}}